apiVersion: v1
appVersion: 1.6.0
description: A Helm chart for running distributed TensorFlow on Kubernetes
home: https://www.tensorflow.org
maintainers:
- email: cheyang@163.com
  name: cheyang
name: distributed-tensorflow
sources:
- https://github.com/tensorflow/tensorflow
- https://www.tensorflow.org/deploy/distributed
version: 0.1.0
