apiVersion: v1
appVersion: 8.0.0
description: Voyager by AppsCode - Secure HAProxy Ingress Controller for Kubernetes
icon: https://cdn.appscode.com/images/icon/voyager.png
maintainers:
- email: support@appscode.com
  name: appscode
name: voyager
sources:
- https://github.com/appscode/voyager
version: 8.0.0
