appVersion: 3.4.3.Final
description: Open Source Identity and Access Management For Modern Applications and
  Services
home: https://www.keycloak.org/
icon: https://www.keycloak.org/resources/images/keycloak_logo_480x108.png
keywords:
- sso
- idm
- openid connect
- saml
- kerberos
- ldap
maintainers:
- email: marcel@beck.im
  name: nexeck
- email: unguiculus@gmail.com
  name: unguiculus
name: keycloak
sources:
- https://github.com/jboss-dockerfiles/keycloak
version: 2.0.0
