apiVersion: v1
appVersion: 1.1.0
description: Hyperledger Fabric Peer chart (these charts are created by AID:Tech and
  are currently not directly associated with the Hyperledger project)
home: http://hyperledger-fabric.readthedocs.io
keywords:
- blockchain
- hyperledger
- fabric
maintainers:
- email: sasha@aid.technology
  name: alexvicegrab
- email: nicola@aid.technology
  name: nicolapaoli
name: hlf-peer
sources:
- https://github.com/hyperledger/fabric
version: 1.0.8
