description: Hashicorp Consul Helm chart for Kubernetes.
home: https://github.com/hashicorp/consul
maintainers:
- email: lachlan@deis.com
  name: Lachlan Evenson
name: consul
sources:
- https://github.com/kelseyhightower/consul-on-kubernetes
version: 0.1.0
