apiVersion: v1
appVersion: 2.2.4
description: Universal component scan for security and license inventory and impact
  analysis
home: https://www.jfrog.com/xray/
icon: https://raw.githubusercontent.com/JFrogDev/artifactory-dcos/master/images/jfrog_med.png
keywords:
- xray
- jfrog
maintainers:
- email: eldada@jfrog.com
  name: eldada
- email: jainishs@jfrog.com
  name: jainishshah17
- email: rimasm@jfrog.com
  name: rimusz
name: xray
sources:
- https://bintray.com/jfrog/product/xray/view
- https://github.com/JFrogDev
version: 0.4.0
