apiVersion: v1
appVersion: 0.4.9
description: CouchDB instance for Hyperledger Fabric (these charts are created by
  AID:Tech and are currently not directly associated with the Hyperledger project)
home: http://hyperledger-fabric.readthedocs.io
keywords:
- blockchain
- hyperledger
- fabric
- couchdb
maintainers:
- email: sasha@aid.technology
  name: alexvicegrab
- email: nicola@aid.technology
  name: nicolapaoli
name: hlf-couchdb
sources:
- https://github.com/hyperledger/fabric
version: 1.0.4
