appVersion: 4.8.4
description: phpMyAdmin is an mysql administration frontend
engine: gotpl
home: https://www.phpmyadmin.net/
icon: https://bitnami.com/assets/stacks/phpmyadmin/img/phpmyadmin-stack-220x234.png
keywords:
- mariadb
- mysql
- phpmyadmin
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: phpmyadmin
sources:
- https://github.com/bitnami/bitnami-docker-phpmyadmin
version: 2.0.2
