apiVersion: v1
appVersion: 0.25.0
description: Prometheus exporter for Redis metrics
home: https://github.com/oliver006/redis_exporter
keywords:
- prometheus
- redis
maintainers:
- email: arcadie.condrat@gmail.com
  name: acondrat
name: prometheus-redis-exporter
sources:
- https://github.com/oliver006/redis_exporter
version: 1.0.1
