apiVersion: v1
appVersion: 0.25.2
description: BookStack is a simple, self-hosted, easy-to-use platform for organising
  and storing information.
home: https://www.bookstackapp.com/
icon: https://github.com/BookStackApp/website/blob/master/static/images/logo.png
maintainers:
- email: bart@verwilst.be
  name: verwilst
name: bookstack
sources:
- https://github.com/BookStackApp/BookStack
version: 1.1.0
