apiVersion: v1
appVersion: 1.1.0
description: A Helm chart for Elastabot - a Slack bot companion for Elasticsearch
  and ElastAlert
engine: gotpl
home: https://github.com/jertel/elastabot
maintainers:
- email: jertel@codesim.com
  name: jertel
name: elastabot
sources:
- https://github.com/jertel/elastabot
version: 1.1.0
