apiVersion: v1
appVersion: 3.0.1
description: nfs-client is an automatic provisioner that used your *already configured*
  NFS server, automatically creating Persistent Volumes.
home: https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client
keywords:
- nfs
- storage
maintainers:
- email: bart@verwilst.be
  name: verwilst
name: nfs-client-provisioner
sources:
- https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client
version: 0.1.1
